language: node_js
os:
  - linux
  - osx
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs-v1.6.4"
install:
  - node --version
  - if [[ ${NODE_VERSION} == "0.8" ]]; then node_modules/.bin/node-gyp rebuild; else node_modules/.bin/pangyp rebuild; fi
script: mocha tests/run
