version: 0.1.2.{build}
os: Windows Server 2012 R2

environment:
  matrix:
  # node.js
  # - nodejs_version: "0.8" mocha does not work on windows with v0.8
  - nodejs_version: "0.10"
  - nodejs_version: "0.12"

platform:
  - x86
  - x64

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

build: off
