var fs = require("fs");
var path = require("path");
var is = require("node-is");

var Const = require("./const");
var pkg = require("./package.json");

var generated = path.join(__dirname, "include", "generated.h");
var cont = "/**\n" +
        " * do not change, this file is autogenerated by 'node build',\n" +
        " * these constants are set in ./const.js\n" +
        " * Build: " + pkg.version + "." + Date.now() + "\n" +
        " */\n" +
        "#ifndef TTYU_GENERATED_H_\n" +
        "#define TTYU_GENERATED_H_\n" +
        "\n";

for(var name in Const) {
    for(var sub in Const[name]) {
        cont += "#define " + name.toUpperCase() + "_" + sub.toUpperCase() +
                " " + toCpp(Const[name][sub]) + "\n";
    }
    cont += "\n";
}

cont += "#endif // TTYU_GENERATED_H_\n";

fs.writeFile(generated, cont, console.log);

function toCpp(v) {
    if(is.String(v)) {
        return "NanNew<v8::String>(\"" + v + "\")";
    } else {
        return v;
    }
}

// TODO node-gyp rebuild
