/**
 * do not change, this file is autogenerated by 'node build'
 * Build: 0.0.2.1425663436594
 */
#ifndef TTYU_GENERATED_H_
#define TTYU_GENERATED_H_

#define EVENT_ERROR 0
#define EVENT_RESIZE 1
#define EVENT_KEY 2
#define EVENT_MOUSEUP 3
#define EVENT_MOUSEDOWN 4
#define EVENT_MOUSEMOVE 5
#define EVENT_MOUSEWHEEL 6
#define EVENT_MOUSEHWHEEL 7

#define MOUSE_LEFT 1
#define MOUSE_LEFT2 4
#define MOUSE_LEFT3 8
#define MOUSE_LEFT4 16
#define MOUSE_RIGHT 2

#define WHICH_UNKNOWN -1

#define CTRL_NULL 0
#define CTRL_ALT 1
#define CTRL_CTRL 2
#define CTRL_SHIFT 4
#define CTRL_ENHANCED 8
#define CTRL_CMD 16
#define CTRL_NUMLOCK 32
#define CTRL_SCROLLLOCK 64
#define CTRL_CAPSLOCK 128

#define MODE_CMD 0
#define MODE_VT102 1
#define MODE_VT100 2

#endif // TTYU_GENERATED_H_
