/**
 * do not change, this file is autogenerated by 'node build'
 * Build: 0.0.2.1425645240302
 */
#ifndef TTYU_GENERATED_H_
#define TTYU_GENERATED_H_

#define EVENT_ERROR 0
#define EVENT_RESIZE 1
#define EVENT_KEY 2
#define EVENT_MOUSEUP 3
#define EVENT_MOUSEDOWN 4
#define EVENT_MOUSEMOVE 5
#define EVENT_MOUSEWHEEL 6
#define EVENT_MOUSEHWHEEL 7

#endif // TTYU_GENERATED_H_
