var path = require("path");
var fs = require("fs");

module.exports = function(ENV) {
  return function(cb) {
    var generated = path.join(__dirname, "..", "include", "generated.h");
    var cont = "/** ttyutil - generated.h - generated header\n" +
               " * https://github.com/clidejs/ttyutil\n" +
               " *\n" +
               " * Copyright Bernhard Bücherl <bernhard.buecherl@gmail.com>\n" +
               " *\n" +
               " * do not change this file,\n" +
               " * it is autogenerated by 'npm install',\n" +
               " * these constants are set in /const.js\n" +
               " */\n" +
               "#ifndef INCLUDE_GENERATED_H_\n" +
               "#define INCLUDE_GENERATED_H_\n" +
               "\n";
    for(var name in ENV.CONST) {
      for(var sub in ENV.CONST[name]) {
        cont += "#define " + name.toUpperCase() + "_" + sub.toUpperCase() +
            " " + toCpp(ENV.CONST[name][sub]) + "\n";
      }
      cont += "\n";
    }
    if(ENV.TTYU_CODE_DEBUG) {
      cont += "#define CDEBUG\n";
      if(ENV.TTYU_CODE_DEBUG === "file") {
        cont += "#define CDEBUG_FILE\n";
      }
      cont += "\n";
    }
    cont += "#endif  // INCLUDE_GENERATED_H_\n";
    console.log("    [preinstall] write constants to 'generated.h'");
    fs.writeFile(generated, cont, function(err) {
      cb(err, 1);
    });
  }
};

function toCpp(v) {
  if(typeof v === "string") {
    return "NanNew<v8::String>(\"" + v + "\")";
  } else {
    return v;
  }
}
